# Generated by Django 4.2.16 on 2024-09-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_remove_cart_username_cart_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart", name="user",),
        migrations.AddField(
            model_name="cart",
            name="username",
            field=models.CharField(default="default_username", max_length=150),
        ),
    ]
