# Generated by Django 4.2.16 on 2024-09-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_remove_cart_user_cart_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart", name="username", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="user",
            field=models.CharField(max_length=255),
        ),
    ]
